version: '3.6'
services:

  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.4-fpm}
    container_name: wordpress
    volumes: &wordpressvolumes
      - ${PHP_CONF_FILE:-./config/php.ini}:/usr/local/etc/php/conf.d/conf.ini
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    environment: &wordpresenvs
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-root}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
    depends_on:
      - mysql
    links:
      - mysql  
    restart: always

  wordpress-cli:
    image: wordpress:${WORDPRESS_CLI_VERSION:-cli-php7.4}
    container_name: wordpress-cli
    entrypoint: wp
    command: "--info"
    volumes: *wordpressvolumes
    environment: *wordpresenvs
    working_dir: /var/www/html
    depends_on:
      - mysql
      - wordpress
    links:
      - mysql  
    restart: always

  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: mysql
    command: --max_allowed_packet=64M
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DATA_DIR:-./mysql}:/var/lib/mysql
      - ${MYSQL_CONF_DIR:-./config/mysql}:/etc/mysql/conf.d
      - ${MYSQL_LOG_DIR:-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    command: 
      - /bin/bash 
      - -c 
      - "envsubst < /etc/nginx/nginx.tpl > /etc/nginx/nginx.conf && \
        envsubst < /etc/nginx/conf.d/default.tpl > /etc/nginx/conf.d/default.conf && \
        nginx -t && nginx -g 'daemon off;'"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_CONF_DIR:-./config/nginx}/nginx.tpl:/etc/nginx/nginx.tpl
      - ${NGINX_CONF_DIR:-./config/nginx}/default.tpl:/etc/nginx/conf.d/default.tpl
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
      - ${SSL_CERTS_DIR:-./certs}:/etc/nginx/certs
    environment:
      DOLLAR: $$
      SERVER_NAME: ${SERVER_NAME:-wordpress.test}
      WORKER_PROCESSES: ${WORKER_PROCESSES:-2}
      WORKER_CONNECTIONS: ${WORKER_CONNECTIONS:-1024}
      WORDPRESS_HOST: wordpress
      WORDPRESS_PORT: 9000
    depends_on:
      - wordpress
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    container_name: phpmyadmin
    volumes:
      - ${PHPMYADMIN_CONF_FILE:-./config/phpmyadmin.ini}:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    ports:
      - 8080:80
    depends_on:
      - mysql
    links:
      - mysql  
    restart: always
